#!/usr/bin/env bash
# Указываем скрипту, в каком графическом окружении работать
export DISPLAY=:0
export XAUTHORITY=$HOME/.Xauthority
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
exec "$HOME/.venv/voice/bin/python" "$DIR/voice-type.py" "$@"